# This file is part of the OmniDiff code diffing tool.
#
# Copyright (C) 2026 Marko Ivankovic
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# The omnidiff derivation, kept separate from flake.nix so it can be imported directly by anyone
# not using flakes (`pkgs.callPackage ./packaging/nix/package.nix { }`) and so a nixpkgs submission
# has a single file to take.
#
# `src` is a parameter rather than a `fetchFromGitHub` call baked in here: the flake at the repo
# root passes the checkout itself, so `nix build` and `nix run` work on a working tree with no tag
# and no hash. A nixpkgs submission would instead pass a `fetchFromGitHub { ... hash = "sha256-..."; }`
# and swap `cargoLock.lockFile` for a `cargoHash`, since nixpkgs does not carry the lock file.
{
  lib,
  rustPlatform,
  installShellFiles,
  git,
  src ? ../..,
  version ? "0.2.0",
}:

rustPlatform.buildRustPackage {
  pname = "omnidiff";
  inherit version src;

  # Avoids needing a vendor hash at all: the lock file is right here in the source tree, so Nix
  # can vendor from it directly instead of being told the hash of a vendor directory it has to
  # build first. This is the reason to prefer a flake in-repo over a nixpkgs-style `cargoHash`.
  cargoLock.lockFile = "${src}/Cargo.lock";

  nativeBuildInputs = [ installShellFiles ];

  # The git review tests (`review::tests`, `tui::app::tests`) build a throwaway repository with
  # the real `git`, which the build sandbox does not otherwise provide. Check-time only: at run
  # time the user's own git is on PATH, and the binary has no git dependency of its own.
  nativeCheckInputs = [ git ];

  # Every tree-sitter grammar is compiled from C. stdenv already supplies the compiler, so there is
  # nothing to add here - but it is why this build is slower than the Rust dependency count alone
  # suggests, and it compounds with the release profile's `lto = "fat"` + `codegen-units = 1`
  # (see Cargo.toml). Expect minutes.

  # Default features only (`tui`), the product binary. `stats`/`test-fixtures` gate
  # dataset-analysis dev tools needing git2 (OpenSSL, libssh2) and a bundled SQLite; they are not
  # part of the shipped product, so they are deliberately not exposed as a Nix option.
  cargoBuildFlags = [ "--bin" "omnidiff" ];

  # --lib only. The fixture-corpus tests are upstream's accuracy benchmark: they need the
  # `test-fixtures` feature and substantial time and memory, which is not what a packaging sanity
  # check is for. (They are also absent entirely if `src` is ever pointed at the crates.io tarball,
  # whose `include` list carries neither tests/ nor src/test/data/.)
  cargoTestFlags = [ "--lib" ];

  # cargo-nextest, as CI and the Makefile run the suite: one process per test. The git review
  # tests change the process working directory, which is harmless in a process of their own and
  # breaks any cwd-relative test sharing the process under plain `cargo test`.
  useNextest = true;

  postInstall = ''
    # Generated by the binary just built, from the same clap definition as --help. This is a
    # native-build assumption: under cross-compilation $out/bin/omnidiff cannot be executed here
    # and these would have to come from a host build instead.
    # A real file: installManPage reads the section from the file name, so a pipe will not do.
    $out/bin/omnidiff util man > omnidiff.1
    installManPage omnidiff.1
    installShellCompletion --cmd omnidiff \
      --bash <($out/bin/omnidiff util completions bash) \
      --zsh <($out/bin/omnidiff util completions zsh) \
      --fish <($out/bin/omnidiff util completions fish)
  '';

  meta = {
    description = "Fast, robust, accurate content-aware diffing";
    longDescription = ''
      OmniDiff parses both sides of a diff with tree-sitter and matches their syntax trees, so a
      change is reported as what it structurally is - an insertion, deletion, update, or move -
      rather than as whichever lines happened to align. It runs as an interactive terminal UI, a
      plain-text batch formatter, or a JSON emitter for editor integrations, and works as a git
      difftool backend and a Jujutsu (jj) diff formatter.
    '';
    homepage = "https://github.com/ivankovic/omnidiff";
    changelog = "https://github.com/ivankovic/omnidiff/releases";
    license = lib.licenses.agpl3Plus;
    mainProgram = "omnidiff";
    maintainers = [ ];
    platforms = lib.platforms.unix ++ lib.platforms.windows;
  };
}
